server:
  servlet:
    context-path: /topjava/

spring:
  profiles:
    active: datajpa
    #active: jpa
    #active: jdbc
#---
#spring:
#  profiles: postgresql
  #PostgreSQL

  datasource:
    schema: classpath:db/initDB.sql
    data: classpath:db/populateDB.sql
    url: jdbc:postgresql://localhost:5432/topjava
    password: password
    username: user
    initialization-mode: always

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20

  cache:
    ehcache:
      config: cache/ehcache.xml

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    locale-resolver: accept_header
    locale: ru
  resources:
    static-locations: /resources/

  messages:
    encoding: UTF-8
    fallback-to-system-locale: false

#---
#spring:
#  profiles: hsqldb
#  datasource:
#    schema: classpath:db/initDB_hsql.sql
#    data: classpath:db/populateDB.sql
#    url: jdbc:hsqldb:mem:topjava
#    password:
#    username: sa
#    initialization-mode: always
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none





